# Generated by Django 4.2 on 2023-04-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('name',), 'verbose_name': 'Chatroom', 'verbose_name_plural': 'Chatrooms'},
        ),
    ]
